name: Run CI Tests
on: [push]
env:
  GO_VERSION: ~1.19
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - name: Run Go Test
        run: |
          go test -race -v ./...

