name: Run CI Tests
on: [push]
jobs:
  run-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          skip-cache: true
  run-copywrite:
    runs-on:
      ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.2
      - name: verify copyright
        run: |
          copywrite headers --plan
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-14
          - windows-2022
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - name: Run Go Test
        run: |
          go test -race -v ./...

