name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-lint:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
          skip-cache: true
  run-copywrite:
    timeout-minutes: 5
    runs-on:
      ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: verify copyright
        run: |
          copywrite headers --plan
  run-tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-14
          - windows-2022
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - name: Run Go Test
        run: |
          go test -race -v ./...

